### ISSUE TITLE
jitpack (gradle) support

### ISSUE THREAD

**Issue by neph1** [oneMillionWorlds/Tamarin#5]
Thanks for this project.

I'm trying to use this via gradle and jitpack, but it fails somehow:
https://jitpack.io/com/github/oneMillionWorlds/Tamarin/1.3/build.log

Could you look into making it compatible? It would make using it considerably easier.
I'm afraid I can't help out why it fails, for my project I didn't have to do anything in particular.

Thanks!

**Comment by neph1** [comment]
I realized it was already on maven central through.
https://github.com/oneMillionWorlds/TamarinTestBed/blob/main/build.gradle
Just add:
implementation 'com.onemillionworlds:tamarin:1.3'

Maybe add to 'getting started'?

**Comment by richardTingle** [comment]
Glad you found the answer. I think that's a good suggestion and I've updated the  'getting started' page.
